[package]
name = "runner-extended"
version = "0.1.0"
edition = "2021"

[dependencies]
runner = { path = "../runner" }
tracing = "0.1.41"

[build-dependencies]
runner = { path = "../runner" }

[lib]
name = "runner_extended"
path = "src/lib.rs"  # Changed from ../runner/src/lib.rs